name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: TBXark/ChatGPT-Telegram-Workers
        source_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: tmp
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: tmp
        destination_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
