name: Sync

on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: TBXark/ChatGPT-Telegram-Workers
        source_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: tmp
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: tmp
        destination_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
